# Generated by Django 4.2 on 2026-09-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('token_number', models.PositiveIntegerField()),
                ('token_type', models.CharField(choices=[('ONLINE', 'Online Token'), ('PHYSICAL', 'Physical Token')], default='ONLINE', max_length=20)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='doctors.doctor')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='members.member')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tokens',
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['doctor', 'date', 'status'], name='tokens_doctor__a76a68_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['member', 'date'], name='tokens_member__de54dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'token_number'), name='unique_token_number_per_doctor_date'),
        ),
    ]
