# Generated by Django 4.2 on 2026-09-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='revisit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_reason',
            field=models.CharField(blank=True, default='General Consultation', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('REVISIT', 'Revisit Scheduled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
