# Generated by Django 4.2 on 2026-09-10 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='hospitals.hospital')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital Staff',
                'verbose_name_plural': 'Hospital Staff',
                'db_table': 'hospital_staff',
            },
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['user', 'hospital'], name='hospital_st_user_id_e14696_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['hospital', 'role'], name='hospital_st_hospita_7a16e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalstaff',
            constraint=models.UniqueConstraint(fields=('user', 'hospital'), name='unique_user_per_hospital'),
        ),
    ]
