# Generated by Django 4.2 on 2026-09-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=15)),
                ('max_daily_capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'db_table': 'doctor_schedules',
            },
        ),
        migrations.CreateModel(
            name='DailyDoctorCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_capacity', models.PositiveIntegerField()),
                ('online_allocated', models.PositiveIntegerField(default=0)),
                ('physical_allocated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_capacities', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Daily Doctor Capacity',
                'verbose_name_plural': 'Daily Doctor Capacities',
                'db_table': 'daily_doctor_capacities',
            },
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day_of_week'), name='unique_schedule_per_doctor_day'),
        ),
        migrations.AddIndex(
            model_name='dailydoctorcapacity',
            index=models.Index(fields=['doctor', 'date'], name='daily_docto_doctor__25a01e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailydoctorcapacity',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_capacity_per_doctor_date'),
        ),
    ]
