# Generated by Django 4.2 on 2026-09-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='custom_relation',
            field=models.CharField(blank=True, default='', help_text='Optional custom relationship (e.g. Father, Mother, Friend)', max_length=100),
        ),
        migrations.AddField(
            model_name='relationship',
            name='custom_relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('SELF', 'Self'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('COUSIN', 'Cousin'), ('AUNTY', 'Aunty'), ('UNCLE', 'Uncle'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], default='SELF', max_length=30),
        ),
    ]
