# Generated by Django 4.2 on 2026-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_custom_relation_relationship_custom_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
