# Generated by Django 4.2 on 2026-09-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Leave',
                'verbose_name_plural': 'Doctor Leaves',
                'db_table': 'doctor_leaves',
            },
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['doctor', 'start_date', 'end_date'], name='doctor_leav_doctor__5fcdb1_idx'),
        ),
    ]
