# Generated by Django 4.2 on 2026-09-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='daily_capacity_limit',
            field=models.IntegerField(default=60, help_text='Doctor default daily appointment token limit'),
        ),
    ]
